version: "2"
linters:
  default: none
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - mnd
    - musttag
    - noctx
    - paralleltest
    - prealloc
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - testpackage
    - unconvert
    - usestdlibvars
  settings:
    gocritic:
      disable-all: true
      enabled-tags:
        - diagnostic
        - performance
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
severity:
  default: warning
formatters:
  enable:
    - gofmt
    - goimports
