[grammar]
prompt = "fix spelling and grammar"

[refactor]
prompt = """\
  You are a Clean Code expert, I have the following code, \
  please refactor it in a more clean and concise way so that my colleagues \
  can maintain the code more easily. Also, explain why you want to refactor \
  the code so that I can add the explanation to the Pull Request.\
  """

[explain]
prompt = """\
  Explain the following code snippet, but not line by line. \
  Give a general overview of the code: \
  why it might have been implemented this way, its purpose, its quirks, and possible improvements, if any.\
  """

[review]
prompt = """\
  Review the following code snippet. \
  Make sure it follows established best practices, is clean, efficient and maintainable. \
  Pay close attention to common mistakes like syntax errors, logic errors, security vulnerabilities, \
  performance and scalability issues, or anything that seems questionable. \
  For each mistake found, explain what is wrong and how to correct or improve it. \
  Give your answer as one bullet point per mistake found.\
  """

# common options for all engines
[refactor.options]
temperature = 0.4

# engine specific options:
[refactor.options-chat]
model = "deepseek-chat"

[refactor.options-complete]

# mixin to use deepseek-reasoner
[r1]
[r1.options]
model = "deepseek-reasoner"
endpointUrl = "https://api.deepseek.com/v1/chat/completions"
requiresAuth = true
tokenPath = "~/.vim/token.ds"
maxTokens = 4096
temperature = 0.6
initialPrompt = ""

# example for proxy
[4om]
[4om.options]
model = "gpt-4o-mini"
endpointUrl = "https://api.openai.com/v1/chat/completions"
requiresAuth = true
tokenPath = "~/.vim/token.oa"
proxy = "http://127.0.0.1:1081"
