unqualified-search-registries = ["docker.io"]

[[registry]]
prefix = "ghcr.io"
location = "ghcr.io"

[[registry.mirror]]
location = "ghcr.dockerproxy.net"

[[registry]]
location = "docker.io"

[[registry.mirror]]
location = "mirror.ccs.tencentyun.com"

[[registry.mirror]]
location = "dockerproxy.net"
